server:
  port: 8222

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            # Students Service Routes
            - id: students-service
              uri: lb://students
              predicates:
                - Path=/api/v1/students/**
              filters:
                - StripPrefix=0

            # Schools Service Routes
            - id: schools-service
              uri: lb://schools
              predicates:
                - Path=/api/v1/schools/**
              filters:
                - StripPrefix=0

# Eureka Configuration
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Logging configuration for debugging
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

management:
  tracing:
    sampling:
        probability: 1.0
