eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8090

spring:
  application:
    name: students
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/students
    username: postgres
    password: safwene17


  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect